/**
 * LQIP (Low Quality Image Placeholder) utilities
 *
 * Provides functions to get LQIP gradient backgrounds for images.
 */

// Import LQIP data generated by generateLqips.ts
let lqips: Record<string, string> = {};

try {
  const lqipData = await import('@assets/lqips.json');
  lqips = lqipData.default as Record<string, string>;
} catch {
  // File doesn't exist yet, will be generated by running pnpm generate:lqips
}

/**
 * Get string representation of image path (handles ImageMetadata objects)
 */
function getImagePathString(imagePath: any): string {
  if (!imagePath) return '';
  if (typeof imagePath === 'object' && 'src' in imagePath) {
    return imagePath.src;
  }
  return String(imagePath);
}

/**
 * Convert image path to LQIP key
 * @param imagePath Full path like /img/cover/1.webp
 * @returns Short key like cover/1.webp
 */
function imagePathToKey(imagePath: any): string {
  const pathStr = getImagePathString(imagePath);
  return pathStr.replace(/^\/img\//, '');
}

/**
 * Get the LQIP gradient CSS for an image
 * @param imagePath Image path (e.g., /img/cover/1.webp)
 * @returns CSS gradient string or undefined if not found
 */
export function getLqipGradient(imagePath: any): string | undefined {
  const pathStr = getImagePathString(imagePath);
  const key = imagePathToKey(pathStr);
  const compact = lqips[key];
  if (compact?.length !== 18) return undefined;

  // Decode compact format: "aabbccddeeff" → 3 hex colors
  const c1 = `#${compact.slice(0, 6)}`;
  const c2 = `#${compact.slice(6, 12)}`;
  const c3 = `#${compact.slice(12, 18)}`;

  return `linear-gradient(135deg, ${c1} 0%, ${c2} 50%, ${c3} 100%)`;
}

/**
 * Check if an image path is external (starts with http)
 */
export function isExternalImage(imagePath: any): boolean {
  const pathStr = getImagePathString(imagePath);
  return pathStr.startsWith('http://') || pathStr.startsWith('https://');
}

/**
 * Get LQIP style for an image
 * Returns background-image style with gradient
 */
export function getLqipStyle(imagePath: any): string | undefined {
  const pathStr = getImagePathString(imagePath);
  if (isExternalImage(pathStr)) {
    return undefined;
  }
  const gradient = getLqipGradient(pathStr);
  return gradient ? `background-image:${gradient}` : undefined;
}

/**
 * Get LQIP props for component usage
 */
export function getLqipProps(imagePath: any): { style?: string; class?: string } {
  const pathStr = getImagePathString(imagePath);
  if (isExternalImage(pathStr)) {
    return { class: 'lqip-fallback' };
  }

  const style = getLqipStyle(pathStr);
  return style ? { style } : {};
}
